In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df =pd.read_csv('sales_clean_csv.csv')

In [3]:
pd.set_option('display.max_columns', None)

In [4]:
df.drop(columns =(['delivery_time_days','is_delayed2','product_name_lenght','product_description_lenght']),inplace=True)

In [5]:
df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,product_category_name,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name_english,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,seller_zip_code_prefix,seller_city,seller_state,payment_sequential,payment_type,payment_installments,payment_value,review_id,review_score,review_creation_date,review_answer_timestamp,day,month,purchase_to_delivery,estimated_to_delivery,purchase_to_delivery_days,delivery_delay_days,is_delayed
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,utilidades_domesticas,4.0,500.0,19.0,8.0,13.0,housewares,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,9350,maua,SP,1.0,credit_card,1.0,18.12,a54f0611adc9ed256b57ede6b6eb5114,4.0,2017-10-11,2017-10-12 03:43:48,2,10,8 days 10:28:40,7 days 02:34:47,8.0,-7.0,0
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,utilidades_domesticas,4.0,500.0,19.0,8.0,13.0,housewares,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,9350,maua,SP,3.0,voucher,1.0,2.00,a54f0611adc9ed256b57ede6b6eb5114,4.0,2017-10-11,2017-10-12 03:43:48,2,10,8 days 10:28:40,7 days 02:34:47,8.0,-7.0,0
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,utilidades_domesticas,4.0,500.0,19.0,8.0,13.0,housewares,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,9350,maua,SP,2.0,voucher,1.0,18.59,a54f0611adc9ed256b57ede6b6eb5114,4.0,2017-10-11,2017-10-12 03:43:48,2,10,8 days 10:28:40,7 days 02:34:47,8.0,-7.0,0
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,1,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.70,22.76,perfumaria,1.0,400.0,19.0,13.0,19.0,perfumery,af07308b275d755c9edb36a90c618231,47813,barreiras,BA,31570,belo horizonte,SP,1.0,boleto,1.0,141.46,8d5266042046a06655c8db133d120ba5,4.0,2018-08-08,2018-08-08 18:37:50,24,7,13 days 18:46:08,5 days 08:32:15,13.0,-5.0,0
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,1,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-13 08:55:23,159.90,19.22,automotivo,1.0,420.0,24.0,19.0,21.0,auto,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO,14840,guariba,SP,1.0,credit_card,3.0,179.12,e73b67b67587f7644d5bd1a52deb1b01,5.0,2018-08-18,2018-08-22 19:07:58,8,8,9 days 09:27:40,17 days 05:53:31,9.0,-17.0,0

In [6]:
df.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date',
       'price', 'freight_value', 'product_category_name', 'product_photos_qty',
       'product_weight_g', 'product_length_cm', 'product_height_cm',
       'product_width_cm', 'product_category_name_english',
       'customer_unique_id', 'customer_zip_code_prefix', 'customer_city',
       'customer_state', 'seller_zip_code_prefix', 'seller_city',
       'seller_state', 'payment_sequential', 'payment_type',
       'payment_installments', 'payment_value', 'review_id', 'review_score',
       'review_creation_date', 'review_answer_timestamp', 'day', 'month',
       'purchase_to_delivery', 'estimated_to_delivery',
       'purchase_to_delivery_days', 'delivery_delay_days', 'is_delayed'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113193 entries, 0 to 113192
Data columns (total 43 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       113193 non-null  object
 1   customer_id                    113193 non-null  object
 2   order_status                   113193 non-null  object
 3   order_purchase_timestamp       113193 non-null  object
 4   order_approved_at              113193 non-null  object
 5   order_delivered_carrier_date   113193 non-null  object
 6   order_delivered_customer_date  113193 non-null  object
 7   order_estimated_delivery_date  113193 non-null  object
 8   order_item_id                  113193 non-null  int64
 9   product_id                     113193 non-null  object
 10  seller_id                      113193 non-null  object
 11  shipping_limit_date            113193 non-null  object
 12  price                          113193 non-null  float64
 13  freight_value                  113193 non-null  float64
 14  product_category_name          113193 non-null  object
 15  product_photos_qty             113193 non-null  float64
 16  product_weight_g               113193 non-null  float64
 17  product_length_cm              113193 non-null  float64
 18  product_height_cm              113193 non-null  float64
 19  product_width_cm               113193 non-null  float64
 20  product_category_name_english  113193 non-null  object
 21  customer_unique_id             113193 non-null  object
 22  customer_zip_code_prefix       113193 non-null  int64
 23  customer_city                  113193 non-null  object
 24  customer_state                 113193 non-null  object
 25  seller_zip_code_prefix         113193 non-null  int64
 26  seller_city                    113193 non-null  object
 27  seller_state                   113193 non-null  object
 28  payment_sequential             113193 non-null  float64
 29  payment_type                   113193 non-null  object
 30  payment_installments           113193 non-null  float64
 31  payment_value                  113193 non-null  float64
 32  review_id                      113193 non-null  object
 33  review_score                   113193 non-null  float64
 34  review_creation_date           113193 non-null  object
 35  review_answer_timestamp        113193 non-null  object
 36  day                            113193 non-null  int64
 37  month                          113193 non-null  int64
 38  purchase_to_delivery           113193 non-null  object
 39  estimated_to_delivery          113193 non-null  object
 40  purchase_to_delivery_days      113193 non-null  float64
 41  delivery_delay_days            113193 non-null  float64
 42  is_delayed                     113193 non-null  int64
dtypes: float64(13), int64(6), object(24)
memory usage: 37.1+ MB

In [8]:
df.shape

(113193, 43)

# converting date columns to datetime object instead of object

#

In [11]:
import pandas as pd

date_columns = ['order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date', 'shipping_limit_date', 'review_creation_date', 'review_answer_timestamp']

for column in df.columns:
    if column in date_columns:
        try:
            df[column] = pd.to_datetime(df[column])
        except Exception as e:
            print(f"Error converting column {column} to datetime: {e}")

print(df.dtypes)

Error converting column review_creation_date to datetime: unconverted data remains when parsing with format "%Y-%m-%d": " 00:00:00", at position 457. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.
order_id                                 object
customer_id                              object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
order_item_id                             int64
product_id                               object
seller_id                                object
shipping_limit_date              datetime64[ns]
price                                   float64
freight_value                           float64
product_category_name                    object
product_photos_qty                      float64
product_weight_g                        float64
product_length_cm                       float64
product_height_cm                       float64
product_width_cm                        float64
product_category_name_english            object
customer_unique_id                       object
customer_zip_code_prefix                  int64
customer_city                            object
customer_state                           object
seller_zip_code_prefix                    int64
seller_city                              object
seller_state                             object
payment_sequential                      float64
payment_type                             object
payment_installments                    float64
payment_value                           float64
review_id                                object
review_score                            float64
review_creation_date                     object
review_answer_timestamp          datetime64[ns]
day                                       int64
month                                     int64
purchase_to_delivery                     object
estimated_to_delivery                    object
purchase_to_delivery_days               float64
delivery_delay_days                     float64
is_delayed                                int64
dtype: object

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113193 entries, 0 to 113192
Data columns (total 43 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       113193 non-null  object
 1   customer_id                    113193 non-null  object
 2   order_status                   113193 non-null  object
 3   order_purchase_timestamp       113193 non-null  datetime64[ns]
 4   order_approved_at              113193 non-null  datetime64[ns]
 5   order_delivered_carrier_date   113193 non-null  datetime64[ns]
 6   order_delivered_customer_date  113193 non-null  datetime64[ns]
 7   order_estimated_delivery_date  113193 non-null  datetime64[ns]
 8   order_item_id                  113193 non-null  int64
 9   product_id                     113193 non-null  object
 10  seller_id                      113193 non-null  object
 11  shipping_limit_date            113193 non-null  datetime64[ns]
 12  price                          113193 non-null  float64
 13  freight_value                  113193 non-null  float64
 14  product_category_name          113193 non-null  object
 15  product_photos_qty             113193 non-null  float64
 16  product_weight_g               113193 non-null  float64
 17  product_length_cm              113193 non-null  float64
 18  product_height_cm              113193 non-null  float64
 19  product_width_cm               113193 non-null  float64
 20  product_category_name_english  113193 non-null  object
 21  customer_unique_id             113193 non-null  object
 22  customer_zip_code_prefix       113193 non-null  int64
 23  customer_city                  113193 non-null  object
 24  customer_state                 113193 non-null  object
 25  seller_zip_code_prefix         113193 non-null  int64
 26  seller_city                    113193 non-null  object
 27  seller_state                   113193 non-null  object
 28  payment_sequential             113193 non-null  float64
 29  payment_type                   113193 non-null  object
 30  payment_installments           113193 non-null  float64
 31  payment_value                  113193 non-null  float64
 32  review_id                      113193 non-null  object
 33  review_score                   113193 non-null  float64
 34  review_creation_date           113193 non-null  object
 35  review_answer_timestamp        113193 non-null  datetime64[ns]
 36  day                            113193 non-null  int64
 37  month                          113193 non-null  int64
 38  purchase_to_delivery           113193 non-null  object
 39  estimated_to_delivery          113193 non-null  object
 40  purchase_to_delivery_days      113193 non-null  float64
 41  delivery_delay_days            113193 non-null  float64
 42  is_delayed                     113193 non-null  int64
dtypes: datetime64[ns](7), float64(13), int64(6), object(17)
memory usage: 37.1+ MB

In [13]:
df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,product_category_name,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name_english,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,seller_zip_code_prefix,seller_city,seller_state,payment_sequential,payment_type,payment_installments,payment_value,review_id,review_score,review_creation_date,review_answer_timestamp,day,month,purchase_to_delivery,estimated_to_delivery,purchase_to_delivery_days,delivery_delay_days,is_delayed
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,utilidades_domesticas,4.0,500.0,19.0,8.0,13.0,housewares,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,9350,maua,SP,1.0,credit_card,1.0,18.12,a54f0611adc9ed256b57ede6b6eb5114,4.0,2017-10-11,2017-10-12 03:43:48,2,10,8 days 10:28:40,7 days 02:34:47,8.0,-7.0,0
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,utilidades_domesticas,4.0,500.0,19.0,8.0,13.0,housewares,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,9350,maua,SP,3.0,voucher,1.0,2.00,a54f0611adc9ed256b57ede6b6eb5114,4.0,2017-10-11,2017-10-12 03:43:48,2,10,8 days 10:28:40,7 days 02:34:47,8.0,-7.0,0
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,utilidades_domesticas,4.0,500.0,19.0,8.0,13.0,housewares,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,9350,maua,SP,2.0,voucher,1.0,18.59,a54f0611adc9ed256b57ede6b6eb5114,4.0,2017-10-11,2017-10-12 03:43:48,2,10,8 days 10:28:40,7 days 02:34:47,8.0,-7.0,0
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,1,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.70,22.76,perfumaria,1.0,400.0,19.0,13.0,19.0,perfumery,af07308b275d755c9edb36a90c618231,47813,barreiras,BA,31570,belo horizonte,SP,1.0,boleto,1.0,141.46,8d5266042046a06655c8db133d120ba5,4.0,2018-08-08,2018-08-08 18:37:50,24,7,13 days 18:46:08,5 days 08:32:15,13.0,-5.0,0
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,1,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-13 08:55:23,159.90,19.22,automotivo,1.0,420.0,24.0,19.0,21.0,auto,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO,14840,guariba,SP,1.0,credit_card,3.0,179.12,e73b67b67587f7644d5bd1a52deb1b01,5.0,2018-08-18,2018-08-22 19:07:58,8,8,9 days 09:27:40,17 days 05:53:31,9.0,-17.0,0