In [1]:
import pandas as pd 
import seaborn as sns

In [2]:
customers_dataset = pd.read_csv('dataset/olist_customers_dataset.csv')
geolocation_dataset = pd.read_csv('dataset/olist_geolocation_dataset.csv')
order_items_dataset = pd.read_csv('dataset/olist_order_items_dataset.csv')
order_payments_dataset = pd.read_csv('dataset/olist_order_payments_dataset.csv')
order_reviews_dataset = pd.read_csv('dataset/olist_order_reviews_dataset.csv')
orders_dataset = pd.read_csv('dataset/olist_orders_dataset.csv')
products_dataset = pd.read_csv('dataset/olist_products_dataset.csv')
sellers_dataset = pd.read_csv('dataset/olist_sellers_dataset.csv')
product_category_name_translation = pd.read_csv('dataset/product_category_name_translation.csv')

In [3]:
customers_dataset

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP
...,...,...,...,...,...
99436,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,3937,sao paulo,SP
99437,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,6764,taboao da serra,SP
99438,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,60115,fortaleza,CE
99439,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,92120,canoas,RS
99440,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,6703,cotia,SP

In [4]:
customers_dataset.shape

(99441, 5)

In [5]:
geolocation_dataset.sample(5) # maybe not needed for now

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
336456,14400,-20.549121,-47.403624,franca,SP
125898,5364,-23.569688,-46.750981,sao paulo,SP
824195,78320,-11.418455,-58.762638,juina,MT
983579,96820,-29.709358,-52.428574,santa cruz do sul,RS
114074,5028,-23.540526,-46.693440,são paulo,SP

In [6]:
order_items_dataset.sample(5)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
73597,a7bf43f042e3cbaa32238547ec22b6ed,2,e94df75b2e9a8b056be0c144a731f55c,5cf13accae3222c70a9cac40818ae839,2017-09-04 04:44:42,94.90,11.83
14467,20eb7eeb96c1d064240b1c21ab810398,1,6413f7a28e149a324c4a914000399fb2,7a67c85e85bb2ce8582c35f2203ad736,2017-10-05 20:14:12,149.99,18.30
112087,fea37071a9fe1444fc1ed7f316b68478,1,7dfb24c54964f42db9b9789bdae92cc0,30a81d8cf85fb2ada1b1b094c9583a95,2018-07-06 00:30:30,34.99,7.51
59778,8833f31fc345a814293e41677c701c27,1,001795ec6f1b187d37335e1c4704762e,8b321bb669392f5163d04c59e235e066,2017-11-29 22:31:38,38.90,9.34
1446,0352f2ba09b99ccae0751e133332a46b,1,97de9cc5ef2b385440117d854522881d,ececbfcff9804a2d6b40f589df8eef2b,2018-07-24 10:30:15,69.50,18.59

In [7]:
order_payments_dataset.sample(5)

,order_id,payment_sequential,payment_type,payment_installments,payment_value
26485,4fd95287834e5721e6dd034110ea149e,1,credit_card,1,35.85
2528,1ab8b3bd6a4d22497ce5164c01bc0e2c,1,boleto,1,63.95
70425,bb310183fd0dc613fbe383644fb159eb,1,credit_card,1,73.78
24792,669b9b0a3650913de5b761ff980d8c06,1,credit_card,2,81.21
64541,0749bdde40245b5fb3b375dadfd4ebe3,1,debit_card,1,71.38

In [8]:
order_reviews_dataset.sample(5)

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
28063,8c08bdddc05f836c4aa1ac221fcc6398,eaa950f3b3db6c1a8f5d884992a997c0,5,NaN,NaN,2018-06-30 00:00:00,2018-06-30 18:32:00
54409,89750cb919b3291b107a2db388a540a5,2bf5740adc026c1b84b93c731d86fade,4,NaN,Modelo de tapete incompatível com o carro desc...,2018-04-07 00:00:00,2018-04-08 01:26:07
29500,86f657da3121c264545d9d70d7c9c1d1,dad25b8109c99779d47475dfa7f54371,5,NaN,NaN,2018-05-11 00:00:00,2018-05-14 00:15:39
955,55876f941470173bcf4d2013be74d18c,3cf35e66383eac0fa651e99728d09c8c,4,NaN,"Chegou antes da data do prazo, porem vazou um ...",2017-11-04 00:00:00,2017-11-05 10:43:54
1548,2c347c96f8719cf7170789d58cc160cb,32b75a504adac9e56f590b0561a5fcc6,4,NaN,NaN,2017-12-10 00:00:00,2017-12-11 11:35:25

In [9]:
orders_dataset

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00
...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00

In [10]:
orders_dataset[orders_dataset['customer_id'] == '06b8999e2fba1a1fbc88172c00ba8bc7']

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
88492,00e7ee1b050b8499577073aeb2a297a1,06b8999e2fba1a1fbc88172c00ba8bc7,delivered,2017-05-16 15:05:35,2017-05-16 15:22:12,2017-05-23 10:47:57,2017-05-25 10:35:35,2017-06-05 00:00:00

In [11]:
products_dataset.sample(5)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
16997,e724a0cc4252ae8385e3b66944b6a3ea,automotivo,60.0,715.0,3.0,1750.0,55.0,27.0,40.0
31054,77f896a49e4b52c7886411acf219f98f,relogios_presentes,28.0,729.0,1.0,500.0,22.0,11.0,11.0
32940,dfec64aac9b864b2807a7be33222b75f,cama_mesa_banho,58.0,252.0,4.0,850.0,38.0,7.0,28.0
32442,e0d89abf7cf8de31e5e7fa03ddba5e2d,telefonia,32.0,346.0,3.0,300.0,17.0,8.0,13.0
24239,833984d7021e50b11df8113b7794e920,esporte_lazer,28.0,1319.0,1.0,400.0,34.0,16.0,16.0

In [12]:
sellers_dataset.sample(5)

,seller_id,seller_zip_code_prefix,seller_city,seller_state
2967,282c7480173bb9c01dd41cc739fec010,4795,sao paulo,SP
1730,2528513dd95219a6013d4d05176e391a,6060,osasco,SP
1364,6338ea67c41078a46ad99cc009654956,95170,farroupilha,RS
1161,5f5b43b2bffa8656e4bc6efeb13cc649,4880,sao paulo,SP
920,dee656f0f566ed1aa85bd137c943f08f,12701,cruzeiro,SP

In [13]:
product_category_name_translation.sample(5)

            product_category_name          product_category_name_english
61                         musica                                  music
40                casa_construcao                      home_construction
21               fashion_calcados                          fashion_shoes
63    portateis_casa_forno_e_cafe  small_appliances_home_oven_and_coffee
44  industria_comercio_e_negocios         industry_commerce_and_business

# insights 
1. Revenue Trends: Monthly/quarterly sales trends, peak seasons (e.g., Black Friday), YoY growth.
        orders, order_items, products, product_category_translation
2. Churn Analysis: Track one-time vs. repeat buyers and factors influencing retention (e.g., delivery delays, poor reviews).
    Tables Involved: customers, orders, geolocation, reviews.

3. Top Categories/Products: Best-selling categories, revenue contribution, and inventory turnover.

4. Product Pairing: Association analysis (e.g., products frequently bought together).

5. Seasonality: Category-specific trends (e.g., gifts in December).
    Tables Involved: order_items, products, product_category_translation.

6. Delivery Delays: Compare estimated vs. actual delivery times. (may affect the seller)

7. Sales Hotspots: States/cities contributing most revenue.

8. Regional Preferences: Product category popularity by region (e.g., warmer states buying more beachwear).

## questions to ask 
Which product categories have the highest customer satisfaction (reviews) but low sales?

Do sellers with faster shipping times receive better reviews?

What payment methods dominate high-value orders?

Which states have the longest delays between order approval and delivery?

Which cities have the highest density of sellers but low customer bases?


How do delivery delays impact review scores?


Which regions have the longest delivery delays, and why?

Are there seasonal spikes in specific product categories (e.g., holidays, festivals)?

Which products are frequently purchased together?

What percentage of customers are repeat buyers vs. one-time purchasers?

Do customers in urban areas (e.g., São Paulo) spend more than those in rural regions?

***What is the average customer lifetime value (CLV) for different regions?

*** How do seller review scores correlate with their order fulfillment speed?

10. if the order is delayed does this affect the review

In [14]:
# Step 1: Translate product categories using product_category_name_translation
# Rename columns in the translation dataset for clarity
product_category_name_translation.rename(columns={
    'product_category_name': 'product_category_name_portuguese',
    'product_category_name_english': 'product_category_name_english'
}, inplace=True)

# Merge products_dataset with the translation dataset
products_dataset = pd.merge(
    products_dataset,
    product_category_name_translation,
    left_on='product_category_name',
    right_on='product_category_name_portuguese',
    how='left'
)

# Drop the Portuguese category column if you only need the English version
products_dataset.drop(columns=['product_category_name_portuguese'], inplace=True)

# Step 2: Merge orders and order items
sales_data = pd.merge(orders_dataset, order_items_dataset, on='order_id', how='inner')

# Step 3: Add product details (including translated categories)
sales_data = pd.merge(sales_data, products_dataset, on='product_id', how='left')

# Step 4: Add customer details
sales_data = pd.merge(sales_data, customers_dataset, on='customer_id', how='left')

# Step 5: Add seller details
sales_data = pd.merge(sales_data, sellers_dataset, on='seller_id', how='left')

# Step 6: Add payment details
sales_data = pd.merge(sales_data, order_payments_dataset, on='order_id', how='left')

# Step 7: Add review details
sales_data = pd.merge(sales_data, order_reviews_dataset, on='order_id', how='left')

In [15]:
pd.set_option('display.max_columns', None)

In [16]:
sales_data

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name_english,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,seller_zip_code_prefix,seller_city,seller_state,payment_sequential,payment_type,payment_installments,payment_value,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0,housewares,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,9350,maua,SP,1.0,credit_card,1.0,18.12,a54f0611adc9ed256b57ede6b6eb5114,4.0,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0,housewares,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,9350,maua,SP,3.0,voucher,1.0,2.00,a54f0611adc9ed256b57ede6b6eb5114,4.0,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0,housewares,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,9350,maua,SP,2.0,voucher,1.0,18.59,a54f0611adc9ed256b57ede6b6eb5114,4.0,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,1,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.70,22.76,perfumaria,29.0,178.0,1.0,400.0,19.0,13.0,19.0,perfumery,af07308b275d755c9edb36a90c618231,47813,barreiras,BA,31570,belo horizonte,SP,1.0,boleto,1.0,141.46,8d5266042046a06655c8db133d120ba5,4.0,Muito boa a loja,Muito bom o produto.,2018-08-08 00:00:00,2018-08-08 18:37:50
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,1,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-13 08:55:23,159.90,19.22,automotivo,46.0,232.0,1.0,420.0,24.0,19.0,21.0,auto,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO,14840,guariba,SP,1.0,credit_card,3.0,179.12,e73b67b67587f7644d5bd1a52deb1b01,5.0,NaN,NaN,2018-08-18 00:00:00,2018-08-22 19:07:58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118305,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00,1,f1d4ce8c6dd66c47bbaa8c6781c2a923,1f9ab4708f3056ede07124aad39a2554,2018-02-12 13:10:37,174.90,20.10,bebes,52.0,828.0,4.0,4950.0,40.0,10.0,40.0,baby,da62f9e57a76d978d02ab5362c509660,11722,praia grande,SP,17602,tupa,SP,1.0,credit_card,3.0,195.00,29bb71b2760d0f876dfa178a76bc4734,4.0,NaN,So uma peça que veio rachado mas tudo bem rs,2018-03-01 00:00:00,2018-03-02 17:50:01
118306,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00,1,b80910977a37536adeddd63663f916ad,d50d79cb34e38265a8649c383dcffd48,2017-09-05 15:04:16,205.99,65.02,eletrodomesticos_2,51.0,500.0,2.0,13300.0,32.0,90.0,22.0,home_appliances_2,737520a9aad80b3fbbdad19b66b37b30,45920,nova vicosa,BA,8290,sao paulo,SP,1.0,credit_card,5.0,271.01,371579771219f6db2d830d50805977bb,5.0,NaN,Foi entregue antes do prazo.,2017-09-22 00:00:00,2017-09-22 23:10:57
118307,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00,1,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,2018-01-12 21:36:21,179.99,40.59,informatica_acessorios,59.0,1893.0,1.0,6550.0,20.0,20.0,20.0,computers_accessories,5097a5312c8b157bb7be58ae360ef43c,28685,japuiba,RJ,37175,ilicinea,MG,1.0,credit_card,4.0,441.16,8ab6855b9fe9b812cd03a480a25058a1,2.0,NaN,Foi entregue somente 1. Quero saber do outro p...,2018-01-26 00:00:00,2018-01-27 09:16:56
118308,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00,2,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,2018-01-12 21:36:21,179.99,40.59,informatica_acessorios,59.0,1893.0,1.0,6550.0,20.0,20.0,20.0,computers_accessories,5097a5312c8b157bb7be58ae360ef43c,28685,japuiba,RJ,37175,ilicinea,MG,1.0,credit_card,4.0,441.16,8ab6855b9fe9b812cd03a480a25058a1,2.0,NaN,Foi entregue somente 1. Quero saber do outro p...,2018-01-26 00:00:00,2018-01-27 09:16:56
118309,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00,1,006619bbed68b000c8ba3f8725d5409e,ececbfcff9804a2d6b40f589df8eef2b,2018-03-15 10:55:42,68.50,18.36,beleza_saude,45.0,569.0,1.0,150.0,16.0,7.0,15.0,health_beauty,60350aa974b26ff12caad89e55993bd6,83750,lapa,PR,14407,franca,SP,1.0,debit_card,1.0,86.86,dc9c59b4688062c25758c2be4cafc523,5.0,NaN,NaN,2018-03-17 00:00:00,2018-03-17 16:33:31

In [17]:
sales_data.sample(5)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name_english,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,seller_zip_code_prefix,seller_city,seller_state,payment_sequential,payment_type,payment_installments,payment_value,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
1463,92ba7c89244ceee45a169b86da9fcada,92ac000d2f928f22b64ae50dc34f652f,delivered,2018-06-06 15:11:03,2018-06-06 15:34:15,2018-06-07 11:19:00,2018-06-11 20:33:22,2018-07-12 00:00:00,1,b369e02eda28d74a9bd658415b08d7fb,77a515caa36327151d1cc6c32a9f00e1,2018-06-14 15:30:52,79.90,16.53,papelaria,42.0,173.0,2.0,700.0,36.0,6.0,29.0,stationery,c3e5206cdb1a0a23a38c01fe7ba95da6,30130,belo horizonte,MG,9912,diadema,SP,1.0,credit_card,1.0,96.43,ebeaa7065131c10697c419c871518dcc,5.0,NaN,NaN,2018-06-12 00:00:00,2018-06-13 00:44:48
117470,734a45cad1f49226013e72303953d6ad,cc2c433fef10e158effe8dc9bba5018d,delivered,2017-08-07 16:35:50,2017-08-07 16:55:19,2017-08-08 22:17:59,2017-08-15 15:13:59,2017-08-29 00:00:00,2,bd481cb85531aa8ef9c09eb9e6a9e0a9,20d83f3ef0e6925fd74bfd59170babf7,2017-08-11 16:55:19,38.90,14.10,fashion_bolsas_e_acessorios,27.0,819.0,1.0,100.0,16.0,5.0,16.0,fashion_bags_accessories,b2d7efad96cd6e0818a695a03507bdbd,31930,belo horizonte,MG,2804,sao paulo,SP,1.0,credit_card,3.0,102.10,bc310a2bc04715e30961a4b5f3fb1b39,5.0,NaN,NaN,2017-08-16 00:00:00,2017-08-21 03:07:03
32038,177ec1b1bde2badda1cbca0f19f1aed4,847ac392fbef8fe1594965d9d4e94d5d,delivered,2018-01-19 17:47:57,2018-01-20 09:10:52,2018-01-22 20:22:03,2018-01-24 21:48:46,2018-02-09 00:00:00,1,d6b21712ba181dea6664f1b3e09d650e,0ef83d7d83ed97cd2a0049ac8be5f88a,2018-01-25 09:10:50,52.17,13.39,esporte_lazer,30.0,1826.0,1.0,360.0,18.0,14.0,16.0,sports_leisure,481ef475da1dac8aeaa1330ae9c3b029,83203,paranagua,PR,80230,curitiba,PR,1.0,boleto,1.0,65.56,affbbf604d6f6c6fae57ace9fce899ff,5.0,NaN,NaN,2018-01-25 00:00:00,2018-01-26 12:58:27
94502,91d34a183e2eae29ccb607481a4d8ca5,633b73891ad4cd4be0bd5f55da98bc99,delivered,2018-08-04 19:38:07,2018-08-04 19:50:08,2018-08-06 19:08:00,2018-08-08 14:52:53,2018-08-24 00:00:00,1,274d4e727ddbeb7c392ea2e551e3a77d,4e06067cc08b3f41d837768d392c3ee3,2018-08-07 19:50:08,7.00,17.06,perfumaria,30.0,138.0,1.0,100.0,20.0,7.0,20.0,perfumery,57e205798923cafb0c9d64142ee1e931,40460,salvador,BA,32604,betim,MG,1.0,credit_card,2.0,24.06,787e8bc93835b5ecc9f7baa156ee28b9,5.0,NaN,NaN,2018-08-09 00:00:00,2018-08-10 13:26:56
93164,d51bd9a2ba2a0c6d76955459164d238d,b88501b556eb6ca99d56add0a47ed16b,delivered,2018-03-30 10:35:24,2018-03-30 11:27:29,2018-04-02 23:28:30,2018-04-04 17:51:09,2018-04-12 00:00:00,1,75c06ee06b201f9b6301d2b5e72993f8,3c7c4a49ec3c6550809089c6a2ca9370,2018-04-05 11:27:29,13.99,7.39,perfumaria,54.0,939.0,1.0,50.0,16.0,5.0,11.0,perfumery,3f537414e06fdda9c61ba1e272979376,8587,itaquaquecetuba,SP,3804,sao paulo,SP,1.0,credit_card,1.0,21.38,8beddcc22e0b4128fd70f021458b1cc7,5.0,NaN,NaN,2018-04-05 00:00:00,2018-04-11 00:05:16

In [18]:
sales_data[sales_data['customer_id']=='06b8999e2fba1a1fbc88172c00ba8bc7']

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name_english,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,seller_zip_code_prefix,seller_city,seller_state,payment_sequential,payment_type,payment_installments,payment_value,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
105115,00e7ee1b050b8499577073aeb2a297a1,06b8999e2fba1a1fbc88172c00ba8bc7,delivered,2017-05-16 15:05:35,2017-05-16 15:22:12,2017-05-23 10:47:57,2017-05-25 10:35:35,2017-06-05 00:00:00,1,a9516a079e37a9c9c36b9b78b10169e8,7c67e1448b00f6e969d365cea6b010ab,2017-05-22 15:22:12,124.99,21.88,moveis_escritorio,41.0,1141.0,1.0,8683.0,54.0,64.0,31.0,office_furniture,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,8577,itaquaquecetuba,SP,1.0,credit_card,2.0,146.87,88b8b52d46df026a9d1ad2136a59b30b,4.0,NaN,NaN,2017-05-26 00:00:00,2017-05-30 22:34:40

In [19]:
sales_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118310 entries, 0 to 118309
Data columns (total 40 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       118310 non-null  object
 1   customer_id                    118310 non-null  object
 2   order_status                   118310 non-null  object
 3   order_purchase_timestamp       118310 non-null  object
 4   order_approved_at              118295 non-null  object
 5   order_delivered_carrier_date   117056 non-null  object
 6   order_delivered_customer_date  115722 non-null  object
 7   order_estimated_delivery_date  118310 non-null  object
 8   order_item_id                  118310 non-null  int64
 9   product_id                     118310 non-null  object
 10  seller_id                      118310 non-null  object
 11  shipping_limit_date            118310 non-null  object
 12  price                          118310 non-null  float64
 13  freight_value                  118310 non-null  float64
 14  product_category_name          116601 non-null  object
 15  product_name_lenght            116601 non-null  float64
 16  product_description_lenght     116601 non-null  float64
 17  product_photos_qty             116601 non-null  float64
 18  product_weight_g               118290 non-null  float64
 19  product_length_cm              118290 non-null  float64
 20  product_height_cm              118290 non-null  float64
 21  product_width_cm               118290 non-null  float64
 22  product_category_name_english  116576 non-null  object
 23  customer_unique_id             118310 non-null  object
 24  customer_zip_code_prefix       118310 non-null  int64
 25  customer_city                  118310 non-null  object
 26  customer_state                 118310 non-null  object
 27  seller_zip_code_prefix         118310 non-null  int64
 28  seller_city                    118310 non-null  object
 29  seller_state                   118310 non-null  object
 30  payment_sequential             118307 non-null  float64
 31  payment_type                   118307 non-null  object
 32  payment_installments           118307 non-null  float64
 33  payment_value                  118307 non-null  float64
 34  review_id                      117332 non-null  object
 35  review_score                   117332 non-null  float64
 36  review_comment_title           13892 non-null   object
 37  review_comment_message         49682 non-null   object
 38  review_creation_date           117332 non-null  object
 39  review_answer_timestamp        117332 non-null  object
dtypes: float64(13), int64(3), object(24)
memory usage: 36.1+ MB

In [20]:
# to know the number of missing values in each column
for column in sales_data.columns:
    null_count = sales_data[column].isnull().sum()
    print(f"Column: {column}, Null Count: {null_count}")

Column: order_id, Null Count: 0
Column: customer_id, Null Count: 0
Column: order_status, Null Count: 0
Column: order_purchase_timestamp, Null Count: 0
Column: order_approved_at, Null Count: 15
Column: order_delivered_carrier_date, Null Count: 1254
Column: order_delivered_customer_date, Null Count: 2588
Column: order_estimated_delivery_date, Null Count: 0
Column: order_item_id, Null Count: 0
Column: product_id, Null Count: 0
Column: seller_id, Null Count: 0
Column: shipping_limit_date, Null Count: 0
Column: price, Null Count: 0
Column: freight_value, Null Count: 0
Column: product_category_name, Null Count: 1709
Column: product_name_lenght, Null Count: 1709
Column: product_description_lenght, Null Count: 1709
Column: product_photos_qty, Null Count: 1709
Column: product_weight_g, Null Count: 20
Column: product_length_cm, Null Count: 20
Column: product_height_cm, Null Count: 20
Column: product_width_cm, Null Count: 20
Column: product_category_name_english, Null Count: 1734
Column: customer_unique_id, Null Count: 0
Column: customer_zip_code_prefix, Null Count: 0
Column: customer_city, Null Count: 0
Column: customer_state, Null Count: 0
Column: seller_zip_code_prefix, Null Count: 0
Column: seller_city, Null Count: 0
Column: seller_state, Null Count: 0
Column: payment_sequential, Null Count: 3
Column: payment_type, Null Count: 3
Column: payment_installments, Null Count: 3
Column: payment_value, Null Count: 3
Column: review_id, Null Count: 978
Column: review_score, Null Count: 978
Column: review_comment_title, Null Count: 104418
Column: review_comment_message, Null Count: 68628
Column: review_creation_date, Null Count: 978
Column: review_answer_timestamp, Null Count: 978

In [21]:
# Calculate percentage of missing values for each column
missing_percent = (sales_data.isnull().sum() / len(sales_data)) * 100

# Filter columns with missing values and format as percentages
missing_percent_formatted = missing_percent[missing_percent > 0].apply(lambda x: f"{x:.2f}%")

# Print the result
print(missing_percent_formatted)

order_approved_at                 0.01%
order_delivered_carrier_date      1.06%
order_delivered_customer_date     2.19%
product_category_name             1.44%
product_name_lenght               1.44%
product_description_lenght        1.44%
product_photos_qty                1.44%
product_weight_g                  0.02%
product_length_cm                 0.02%
product_height_cm                 0.02%
product_width_cm                  0.02%
product_category_name_english     1.47%
payment_sequential                0.00%
payment_type                      0.00%
payment_installments              0.00%
payment_value                     0.00%
review_id                         0.83%
review_score                      0.83%
review_comment_title             88.26%
review_comment_message           58.01%
review_creation_date              0.83%
review_answer_timestamp           0.83%
dtype: object

In [22]:
# here to see what is in the review_comment_title column
sales_data['review_comment_title'].head(30)

0                  NaN
1                  NaN
2                  NaN
3     Muito boa a loja
4                  NaN
5                  NaN
6                  NaN
7                  NaN
8                  NaN
9                  NaN
10                 NaN
11                 NaN
12                 NaN
13                 NaN
14                 NaN
15                 NaN
16                 NaN
17                 NaN
18                 NaN
19            Nota dez
20                 NaN
21                 NaN
22                 NaN
23                 NaN
24                 NaN
25                 NaN
26                 NaN
27                 NaN
28                 NaN
29                 NaN
Name: review_comment_title, dtype: object

In [23]:
sales_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118310 entries, 0 to 118309
Data columns (total 40 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       118310 non-null  object
 1   customer_id                    118310 non-null  object
 2   order_status                   118310 non-null  object
 3   order_purchase_timestamp       118310 non-null  object
 4   order_approved_at              118295 non-null  object
 5   order_delivered_carrier_date   117056 non-null  object
 6   order_delivered_customer_date  115722 non-null  object
 7   order_estimated_delivery_date  118310 non-null  object
 8   order_item_id                  118310 non-null  int64
 9   product_id                     118310 non-null  object
 10  seller_id                      118310 non-null  object
 11  shipping_limit_date            118310 non-null  object
 12  price                          118310 non-null  float64
 13  freight_value                  118310 non-null  float64
 14  product_category_name          116601 non-null  object
 15  product_name_lenght            116601 non-null  float64
 16  product_description_lenght     116601 non-null  float64
 17  product_photos_qty             116601 non-null  float64
 18  product_weight_g               118290 non-null  float64
 19  product_length_cm              118290 non-null  float64
 20  product_height_cm              118290 non-null  float64
 21  product_width_cm               118290 non-null  float64
 22  product_category_name_english  116576 non-null  object
 23  customer_unique_id             118310 non-null  object
 24  customer_zip_code_prefix       118310 non-null  int64
 25  customer_city                  118310 non-null  object
 26  customer_state                 118310 non-null  object
 27  seller_zip_code_prefix         118310 non-null  int64
 28  seller_city                    118310 non-null  object
 29  seller_state                   118310 non-null  object
 30  payment_sequential             118307 non-null  float64
 31  payment_type                   118307 non-null  object
 32  payment_installments           118307 non-null  float64
 33  payment_value                  118307 non-null  float64
 34  review_id                      117332 non-null  object
 35  review_score                   117332 non-null  float64
 36  review_comment_title           13892 non-null   object
 37  review_comment_message         49682 non-null   object
 38  review_creation_date           117332 non-null  object
 39  review_answer_timestamp        117332 non-null  object
dtypes: float64(13), int64(3), object(24)
memory usage: 36.1+ MB

In [24]:
sales_data['review_comment_message'].head(30)

0     Não testei o produto ainda, mas ele veio corre...
1     Não testei o produto ainda, mas ele veio corre...
2     Não testei o produto ainda, mas ele veio corre...
3                                  Muito bom o produto.
4                                                   NaN
5     O produto foi exatamente o que eu esperava e e...
6                                                   NaN
7                                                   NaN
8                  fiquei triste por n ter me atendido.
9                                                   NaN
10                                                  NaN
11                                                  NaN
12                                                  NaN
13                           Aguardando retorno da loja
14                           Aguardando retorno da loja
15                                                  NaN
16                                                  NaN
17                                                  NaN
18                                    Gostei do produto
19    Obrigado pela atenção. Lojas lannister perfeit...
20                                                  NaN
21                                                  NaN
22                                                  NaN
23                                                  NaN
24                                                  NaN
25                                                  NaN
26    os correios estäo em greve... näo recebi nenhu...
27                                                  NaN
28                                                  NaN
29                                                  NaN
Name: review_comment_message, dtype: object

In [25]:
# decided to drop the review_comment_title column as it doesn't show any useful information

# Drop rows with any missing values
sales_data_cleaned = sales_data.dropna()

# Or drop rows with missing values in specific columns
sales_data_cleaned = sales_data.dropna(subset=['price', 'freight_value'])

In [26]:
#sales_data.drop(columns=['review_comment_message', 'review_comment_title'], inplace=True)

In [27]:
sales_data.shape

(118310, 40)

In [28]:
# here i will drop the rows with missing values in the dataframe

In [29]:
sales_data_cleaned = sales_data

In [30]:
sales_data_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118310 entries, 0 to 118309
Data columns (total 40 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       118310 non-null  object
 1   customer_id                    118310 non-null  object
 2   order_status                   118310 non-null  object
 3   order_purchase_timestamp       118310 non-null  object
 4   order_approved_at              118295 non-null  object
 5   order_delivered_carrier_date   117056 non-null  object
 6   order_delivered_customer_date  115722 non-null  object
 7   order_estimated_delivery_date  118310 non-null  object
 8   order_item_id                  118310 non-null  int64
 9   product_id                     118310 non-null  object
 10  seller_id                      118310 non-null  object
 11  shipping_limit_date            118310 non-null  object
 12  price                          118310 non-null  float64
 13  freight_value                  118310 non-null  float64
 14  product_category_name          116601 non-null  object
 15  product_name_lenght            116601 non-null  float64
 16  product_description_lenght     116601 non-null  float64
 17  product_photos_qty             116601 non-null  float64
 18  product_weight_g               118290 non-null  float64
 19  product_length_cm              118290 non-null  float64
 20  product_height_cm              118290 non-null  float64
 21  product_width_cm               118290 non-null  float64
 22  product_category_name_english  116576 non-null  object
 23  customer_unique_id             118310 non-null  object
 24  customer_zip_code_prefix       118310 non-null  int64
 25  customer_city                  118310 non-null  object
 26  customer_state                 118310 non-null  object
 27  seller_zip_code_prefix         118310 non-null  int64
 28  seller_city                    118310 non-null  object
 29  seller_state                   118310 non-null  object
 30  payment_sequential             118307 non-null  float64
 31  payment_type                   118307 non-null  object
 32  payment_installments           118307 non-null  float64
 33  payment_value                  118307 non-null  float64
 34  review_id                      117332 non-null  object
 35  review_score                   117332 non-null  float64
 36  review_comment_title           13892 non-null   object
 37  review_comment_message         49682 non-null   object
 38  review_creation_date           117332 non-null  object
 39  review_answer_timestamp        117332 non-null  object
dtypes: float64(13), int64(3), object(24)
memory usage: 36.1+ MB

In [31]:
def calculate_missing_value_percentages(df):
    """
    Calculate and display the percentage of missing values for each column in the DataFrame.

    Parameters:
        df (pd.DataFrame): The input DataFrame to analyze.

    Returns:
        pd.Series: A Series containing the missing value percentages for columns with missing values.
    """
    # Calculate percentage of missing values for each column
    missing_percent = (df.isnull().sum() / len(df)) * 100
    
    # Filter columns with missing values and format as percentages
    missing_percent_formatted = missing_percent[missing_percent > 0].apply(lambda x: f"{x:.2f}%")
    
    # Print the result
    if not missing_percent_formatted.empty:
        print("Columns with Missing Values (%):")
        print(missing_percent_formatted)
    else:
        print("No missing values found in the DataFrame.")
    
    # Return the formatted Series for further use if

In [32]:
calculate_missing_value_percentages(sales_data_cleaned)

Columns with Missing Values (%):
order_approved_at                 0.01%
order_delivered_carrier_date      1.06%
order_delivered_customer_date     2.19%
product_category_name             1.44%
product_name_lenght               1.44%
product_description_lenght        1.44%
product_photos_qty                1.44%
product_weight_g                  0.02%
product_length_cm                 0.02%
product_height_cm                 0.02%
product_width_cm                  0.02%
product_category_name_english     1.47%
payment_sequential                0.00%
payment_type                      0.00%
payment_installments              0.00%
payment_value                     0.00%
review_id                         0.83%
review_score                      0.83%
review_comment_title             88.26%
review_comment_message           58.01%
review_creation_date              0.83%
review_answer_timestamp           0.83%
dtype: object

In [33]:
sales_data_cleaned.drop(columns=['review_comment_message', 'review_comment_title'],inplace = True)

In [34]:
calculate_missing_value_percentages(sales_data)

Columns with Missing Values (%):
order_approved_at                0.01%
order_delivered_carrier_date     1.06%
order_delivered_customer_date    2.19%
product_category_name            1.44%
product_name_lenght              1.44%
product_description_lenght       1.44%
product_photos_qty               1.44%
product_weight_g                 0.02%
product_length_cm                0.02%
product_height_cm                0.02%
product_width_cm                 0.02%
product_category_name_english    1.47%
payment_sequential               0.00%
payment_type                     0.00%
payment_installments             0.00%
payment_value                    0.00%
review_id                        0.83%
review_score                     0.83%
review_creation_date             0.83%
review_answer_timestamp          0.83%
dtype: object

In [35]:
print(sales_data_cleaned.shape)

(118310, 38)

In [36]:
calculate_missing_value_percentages(sales_data_cleaned)

Columns with Missing Values (%):
order_approved_at                0.01%
order_delivered_carrier_date     1.06%
order_delivered_customer_date    2.19%
product_category_name            1.44%
product_name_lenght              1.44%
product_description_lenght       1.44%
product_photos_qty               1.44%
product_weight_g                 0.02%
product_length_cm                0.02%
product_height_cm                0.02%
product_width_cm                 0.02%
product_category_name_english    1.47%
payment_sequential               0.00%
payment_type                     0.00%
payment_installments             0.00%
payment_value                    0.00%
review_id                        0.83%
review_score                     0.83%
review_creation_date             0.83%
review_answer_timestamp          0.83%
dtype: object

# here converting date columns that are objects to datetime type

In [37]:
date_columns = ['order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date', 'shipping_limit_date','review_creation_date', 'review_answer_timestamp']

for column in sales_data_cleaned.columns:
    if column in date_columns:
        sales_data_cleaned[column] = pd.to_datetime(sales_data_cleaned[column])

sales_data_cleaned.dtypes

order_id                                 object
customer_id                              object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
order_item_id                             int64
product_id                               object
seller_id                                object
shipping_limit_date              datetime64[ns]
price                                   float64
freight_value                           float64
product_category_name                    object
product_name_lenght                     float64
product_description_lenght              float64
product_photos_qty                      float64
product_weight_g                        float64
product_length_cm                       float64
product_height_cm                       float64
product_width_cm                        float64
product_category_name_english            object
customer_unique_id                       object
customer_zip_code_prefix                  int64
customer_city                            object
customer_state                           object
seller_zip_code_prefix                    int64
seller_city                              object
seller_state                             object
payment_sequential                      float64
payment_type                             object
payment_installments                    float64
payment_value                           float64
review_id                                object
review_score                            float64
review_creation_date             datetime64[ns]
review_answer_timestamp          datetime64[ns]
dtype: object

In [38]:
sales_data_cleaned['order_delivered_carrier_date']

0        2017-10-04 19:55:00
1        2017-10-04 19:55:00
2        2017-10-04 19:55:00
3        2018-07-26 14:31:00
4        2018-08-08 13:50:00
                 ...
118305   2018-02-07 23:22:42
118306   2017-08-28 20:52:26
118307   2018-01-12 15:35:03
118308   2018-01-12 15:35:03
118309   2018-03-09 22:11:59
Name: order_delivered_carrier_date, Length: 118310, dtype: datetime64[ns]

In [39]:
print(f"Duplicate orders: {sales_data_cleaned.duplicated(subset=['order_id']).sum()}")

Duplicate orders: 19644

In [40]:
# Check duplicates based on order_id + product_id + seller_id (common columns for uniqueness)
cols_to_check = ['order_id', 'product_id', 'seller_id', 'price', 'order_item_id']
duplicate_count = sales_data_cleaned.duplicated(subset=cols_to_check).sum()
print(f"Duplicate rows (based on order_id + product_id + seller_id + price): {duplicate_count}")

Duplicate rows (based on order_id + product_id + seller_id + price): 5660

import matplotlib.pyplot as plt

# Function to identify outliers using IQR method
def find_outliers(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    return df[(df[column] < lower_bound) | (df[column] > upper_bound)]

# Identify outliers for all numerical columns
outliers_dict = {}
for column in sales_data_cleaned.select_dtypes(include=['float64', 'int64']).columns:
    outliers_dict[column] = find_outliers(sales_data_cleaned, column)

# Visualize outliers for each column using box plots
for column in sales_data_cleaned.select_dtypes(include=['float64', 'int64']).columns:
    plt.figure(figsize=(10, 6))
    sns.boxplot(x=sales_data_cleaned[column])
    plt.title(f'Box plot for {column}')
    plt.show()

In [41]:
sales_data_cleaned.shape

(118310, 38)

In [42]:
sales_data_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118310 entries, 0 to 118309
Data columns (total 38 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       118310 non-null  object
 1   customer_id                    118310 non-null  object
 2   order_status                   118310 non-null  object
 3   order_purchase_timestamp       118310 non-null  datetime64[ns]
 4   order_approved_at              118295 non-null  datetime64[ns]
 5   order_delivered_carrier_date   117056 non-null  datetime64[ns]
 6   order_delivered_customer_date  115722 non-null  datetime64[ns]
 7   order_estimated_delivery_date  118310 non-null  datetime64[ns]
 8   order_item_id                  118310 non-null  int64
 9   product_id                     118310 non-null  object
 10  seller_id                      118310 non-null  object
 11  shipping_limit_date            118310 non-null  datetime64[ns]
 12  price                          118310 non-null  float64
 13  freight_value                  118310 non-null  float64
 14  product_category_name          116601 non-null  object
 15  product_name_lenght            116601 non-null  float64
 16  product_description_lenght     116601 non-null  float64
 17  product_photos_qty             116601 non-null  float64
 18  product_weight_g               118290 non-null  float64
 19  product_length_cm              118290 non-null  float64
 20  product_height_cm              118290 non-null  float64
 21  product_width_cm               118290 non-null  float64
 22  product_category_name_english  116576 non-null  object
 23  customer_unique_id             118310 non-null  object
 24  customer_zip_code_prefix       118310 non-null  int64
 25  customer_city                  118310 non-null  object
 26  customer_state                 118310 non-null  object
 27  seller_zip_code_prefix         118310 non-null  int64
 28  seller_city                    118310 non-null  object
 29  seller_state                   118310 non-null  object
 30  payment_sequential             118307 non-null  float64
 31  payment_type                   118307 non-null  object
 32  payment_installments           118307 non-null  float64
 33  payment_value                  118307 non-null  float64
 34  review_id                      117332 non-null  object
 35  review_score                   117332 non-null  float64
 36  review_creation_date           117332 non-null  datetime64[ns]
 37  review_answer_timestamp        117332 non-null  datetime64[ns]
dtypes: datetime64[ns](8), float64(13), int64(3), object(14)
memory usage: 34.3+ MB

In [43]:
# Ensure datetime columns are properly formatted
date_cols = [
    'order_purchase_timestamp',
    'order_delivered_customer_date',
    'order_estimated_delivery_date'
]

for col in date_cols:
    sales_data_cleaned[col] = pd.to_datetime(sales_data_cleaned[col])

# Add the new columns
sales_data_cleaned['day'] = sales_data_cleaned['order_purchase_timestamp'].dt.day
sales_data_cleaned['month'] = sales_data_cleaned['order_purchase_timestamp'].dt.month
sales_data_cleaned['purchase_to_delivery'] = sales_data_cleaned['order_delivered_customer_date'] - sales_data_cleaned['order_purchase_timestamp']
sales_data_cleaned['estimated_to_delivery'] = sales_data_cleaned['order_estimated_delivery_date'] - sales_data_cleaned['order_delivered_customer_date']

# Optional: Convert time deltas to numeric days
sales_data_cleaned['purchase_to_delivery_days'] = sales_data_cleaned['purchase_to_delivery'].dt.days
sales_data_cleaned['delivery_delay_days'] = sales_data_cleaned['estimated_to_delivery'].dt.days * -1  # Positive = delay

In [44]:
sales_data_cleaned.head(10)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name_english,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,seller_zip_code_prefix,seller_city,seller_state,payment_sequential,payment_type,payment_installments,payment_value,review_id,review_score,review_creation_date,review_answer_timestamp,day,month,purchase_to_delivery,estimated_to_delivery,purchase_to_delivery_days,delivery_delay_days
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0,housewares,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,9350,maua,SP,1.0,credit_card,1.0,18.12,a54f0611adc9ed256b57ede6b6eb5114,4.0,2017-10-11,2017-10-12 03:43:48,2,10,8 days 10:28:40,7 days 02:34:47,8.0,-7.0
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0,housewares,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,9350,maua,SP,3.0,voucher,1.0,2.00,a54f0611adc9ed256b57ede6b6eb5114,4.0,2017-10-11,2017-10-12 03:43:48,2,10,8 days 10:28:40,7 days 02:34:47,8.0,-7.0
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0,housewares,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,9350,maua,SP,2.0,voucher,1.0,18.59,a54f0611adc9ed256b57ede6b6eb5114,4.0,2017-10-11,2017-10-12 03:43:48,2,10,8 days 10:28:40,7 days 02:34:47,8.0,-7.0
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,1,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.70,22.76,perfumaria,29.0,178.0,1.0,400.0,19.0,13.0,19.0,perfumery,af07308b275d755c9edb36a90c618231,47813,barreiras,BA,31570,belo horizonte,SP,1.0,boleto,1.0,141.46,8d5266042046a06655c8db133d120ba5,4.0,2018-08-08,2018-08-08 18:37:50,24,7,13 days 18:46:08,5 days 08:32:15,13.0,-5.0
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,1,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-13 08:55:23,159.90,19.22,automotivo,46.0,232.0,1.0,420.0,24.0,19.0,21.0,auto,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO,14840,guariba,SP,1.0,credit_card,3.0,179.12,e73b67b67587f7644d5bd1a52deb1b01,5.0,2018-08-18,2018-08-22 19:07:58,8,8,9 days 09:27:40,17 days 05:53:31,9.0,-17.0
5,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,1,d0b61bfb1de832b15ba9d266ca96e5b0,66922902710d126a0e7d26b0e3805106,2017-11-23 19:45:59,45.00,27.20,pet_shop,59.0,468.0,3.0,450.0,30.0,10.0,20.0,pet_shop,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN,31842,belo horizonte,MG,1.0,credit_card,1.0,72.20,359d03e676b3c069f62cadba8dd3f6e8,5.0,2017-12-03,2017-12-05 19:21:58,18,11,13 days 05:00:36,12 days 23:31:18,13.0,-12.0
6,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,1,65266b2da20d04dbe00c5c2d3bb7859e,2c9e548be18521d1c43cde1c582c6de8,2018-02-19 20:31:37,19.90,8.72,papelaria,38.0,316.0,4.0,250.0,51.0,15.0,15.0,stationery,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,SP,8752,mogi das cruzes,SP,1.0,credit_card,1.0,28.62,e50934924e227544ba8246aeb3770dd4,5.0,2018-02-17,2018-02-18 13:02:51,13,2,2 days 20:58:23,9 days 05:42:58,2.0,-9.0
7,a4591c265e18cb1dcee52889e2d8acc3,503740e9ca751ccdda7ba28e9ab8f608,delivered,2017-07-09 21:57:05,2017-07-09 22:10:13,2017-07-11 14:58:04,2017-07-26 10:57:55,2017-08-01,1,060cb19345d90064d1015407193c233d,8581055ce74af1daba164fdbd55a40de,2017-07-13 22:10:13,147.90,27.36,automotivo,49.0,608.0,1.0,7150.0,65.0,10.0,65.0,auto,80bb27c7c16e8f973207a5086ab329e2,86320,congonhinhas,PR,7112,guarulhos,SP,1.0,credit_card,6.0,175.26,89b738e70a1ce346db29a20fb2910161,4.0,2017-07-27,2017-07-27 22:48:30,9,7,16 days 13:00:50,5 days 13:02:05,16.0,-5.0
8,136cce7faa42fdb2cefd53fdc79a6098,ed0271e0b7da060a393796590e7b737a,invoiced,2017-04-11 12:22:08,2017-04-13 13:25:17,NaT,NaT,2017-05-09,1,a1804276d9941ac0733cfd409f5206eb,dc8798cbf453b7e0f98745e396cc5616,2017-04-19 13:25:17,49.90,16.05,NaN,NaN,NaN,NaN,600.0,35.0,35.0,15.0,NaN,36edbb3fb164b1f16485364b6fb04c73,98900,santa rosa,RS,5455,sao paulo,SP,1.0,credit_card,1.0,65.95,e07549ef5311abcc92ba1784b093fb56,2.0,2017-05-13,2017-05-13 20:25:42,11,4,NaT,NaT,NaN,NaN
9,6514b8ad8028c9f2cc2374ded245783f,9bdf08b4b3b52b5526ff42d37d47f222,delivered,2017-05-16 13:10:30,2017-05-16 13:22:11,2017-05-22 10:07:46,2017-05-26 12:55:51,2017-06-07,1,4520766ec412348b8d4caa5e8a18c464,16090f2ca825584b5a147ab24aa30c86,2017-05-22 13:22:11,59.99,15.17,automotivo,59.0,956.0,1.0,50.0,16.0,16.0,17.0,auto,932afa1e708222e5821dac9cd5db4cae,26525,nilopolis,RJ,12940,atibaia,SP,1.0,credit_card,3.0,75.16,07d67dd06ed5f88bef11ef6b464e79ae,5.0,2017-05-27,2017-05-28 02:59:57,16,5,9 days 23:45:21,11 days 11:04:09,9.0,-11.0

In [45]:
#this is just for test

another_sales_test = sales_data_cleaned.copy()
another_sales_test['is_delayed'] = (
    another_sales_test['order_delivered_customer_date'] > 
    another_sales_test['order_estimated_delivery_date']
).astype(int)

In [46]:
another_sales_test.sample(10)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name_english,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,seller_zip_code_prefix,seller_city,seller_state,payment_sequential,payment_type,payment_installments,payment_value,review_id,review_score,review_creation_date,review_answer_timestamp,day,month,purchase_to_delivery,estimated_to_delivery,purchase_to_delivery_days,delivery_delay_days,is_delayed
19395,c12b8710085638bf3b7deee3f4d14db9,b567379ff604724e8cd07c7ea01239c6,delivered,2017-05-17 19:00:56,2017-05-18 02:31:37,2017-05-18 10:24:39,2017-05-22 06:32:43,2017-06-08,1,5a6e53c3b4e8684b13388d6aa4afdf12,7299e27ed73d2ad986de7f7c77d919fa,2017-05-24 02:30:49,16.99,15.10,utilidades_domesticas,45.0,176.0,2.0,200.0,19.0,9.0,12.0,housewares,3e4ff24b051b3808294d9c5f0ca9678d,4026,sao paulo,SP,38440,araguari,MG,1.0,boleto,1.0,32.09,a1f3beb58ada3b8f9a20f2fad862be9d,5.0,2017-05-23,2017-05-23 23:51:11,17,5,4 days 11:31:47,16 days 17:27:17,4.0,-16.0,0
9583,6f95997d009a6c89f18029f779a6de56,d0059e82d12bd59f23e4e09b322e8d57,delivered,2018-02-05 10:16:36,2018-02-05 10:35:36,2018-02-05 20:12:25,2018-03-18 16:19:43,2018-03-06,1,77cc62dc80ebe12a0452d1ce0565acdc,218d46b86c1881d022bce9c68a7d4b15,2018-02-09 10:35:36,113.00,21.28,esporte_lazer,45.0,2950.0,1.0,1625.0,29.0,21.0,21.0,sports_leisure,ddf6b5e5b8bb27ef61ddd976e9b3e37e,22763,rio de janeiro,RJ,14070,ribeirao preto,SP,2.0,credit_card,3.0,82.29,140938a2a4b53afaf4a63fa1dbdc9b03,1.0,2018-03-08,2018-03-09 17:26:30,5,2,41 days 06:03:07,-13 days +07:40:17,41.0,13.0,1
107907,1218b7b8dcee5607631650cd962f6436,70760f5ca54f7826fbc14b679eb949bd,delivered,2018-02-20 20:24:15,2018-02-21 12:05:38,2018-02-22 18:25:09,2018-03-05 20:53:04,2018-03-20,1,617186c3d97ea56c9c683a8a3974e8c1,cc419e0650a3c5ba77189a1882b7556a,2018-03-01 11:31:33,79.99,19.10,perfumaria,59.0,1071.0,1.0,550.0,21.0,12.0,20.0,perfumery,dbfb5a09b90d70b95d25bff85340ffc0,60543,fortaleza,CE,9015,santo andre,SP,1.0,credit_card,4.0,99.09,7521bd9067519e3c35d05884aa72f5a4,5.0,2018-03-06,2018-03-07 01:30:06,20,2,13 days 00:28:49,14 days 03:06:56,13.0,-14.0,0
11360,8d3c15519d40227c3bcca13bb5bbf6d2,b367e7f1a5b42e9bcd14d91190ff9db4,delivered,2017-10-03 13:09:28,2017-10-03 13:24:27,2017-10-04 18:11:35,2017-10-18 19:42:11,2017-10-26,1,42ed7ff87eec051d7f9364afbf091dd3,4e7c18b98d84e05cbae3ff0ff03846c2,2017-10-09 13:24:27,109.00,69.64,eletroportateis,53.0,361.0,1.0,15200.0,37.0,55.0,37.0,small_appliances,4ef1b904f1f96de8003c5982e1201815,21545,rio de janeiro,RJ,14882,jaboticabal,SP,1.0,credit_card,1.0,178.64,d7b8701c531bc6335853022d5ad9a444,2.0,2017-10-19,2017-10-22 02:17:21,3,10,15 days 06:32:43,7 days 04:17:49,15.0,-7.0,0
22734,e127e496849462216ba78b6dfe0c48ed,4e1eea7b0e7ae6e0ed69d9017f4641bc,delivered,2018-05-01 17:38:20,2018-05-03 04:12:48,2018-05-04 15:46:00,2018-05-14 19:03:33,2018-06-01,1,422879e10f46682990de24d770e7f83d,1f50f920176fa81dab994f9023523100,2018-05-09 04:12:48,53.90,6.43,ferramentas_jardim,56.0,348.0,2.0,1550.0,30.0,22.0,30.0,garden_tools,a029899dd8534557a81c369475ff80c8,75650,morrinhos,GO,15025,sao jose do rio preto,SP,1.0,boleto,1.0,177.77,8fee400643053de10d3f1862bdc37ae8,5.0,2018-05-15,2018-05-21 12:08:26,1,5,13 days 01:25:13,17 days 04:56:27,13.0,-17.0,0
57677,9ecc7884797c901042fe3114f1e59f5f,cc89835f7bbd6f0ab15a0b5594605998,delivered,2017-12-09 17:41:47,2017-12-12 03:39:34,2017-12-14 00:38:42,2018-01-03 16:16:36,2018-01-09,1,9e4d5a527ce5c7b4fd84f460c035c3c5,b499c00f28f4b7069ff6550af8c1348a,2017-12-18 03:39:34,59.99,16.18,moveis_decoracao,49.0,171.0,3.0,700.0,16.0,5.0,20.0,furniture_decor,8828868edd8b70cfd28432b5598f1842,29830,nova venecia,ES,13481,limeira,SP,1.0,boleto,1.0,76.17,60dc762be8268467d1052937be6c4838,5.0,2018-01-04,2018-01-06 18:37:32,9,12,24 days 22:34:49,5 days 07:43:24,24.0,-5.0,0
106173,4123f9252f0d0572f075dbb5a95d9cc6,72d22223828ebe8d8f4529ba06e89871,delivered,2018-08-26 16:34:35,2018-08-26 16:45:08,2018-08-27 14:50:00,2018-08-30 18:51:44,2018-09-06,1,73326828aa5efe1ba096223de496f596,d13e50eaa47b4cbe9eb81465865d8cfc,2018-08-28 16:45:08,85.90,13.26,alimentos,32.0,1392.0,1.0,330.0,20.0,15.0,16.0,food,44a64df27a7de57ff4df2aa426acabcf,14787,barretos,SP,9210,santo andre,SP,1.0,debit_card,1.0,99.16,aa7ca8832de5904d00f23acb15d72284,5.0,2018-08-31,2018-09-01 00:29:35,26,8,4 days 02:17:09,6 days 05:08:16,4.0,-6.0,0
96107,ff41c61254c0df3698b8689d9493ffb0,2a5f9b176a5e7313e3836750a5dde869,delivered,2018-02-23 09:16:59,2018-02-23 09:31:02,2018-02-26 10:45:36,2018-03-27 20:18:29,2018-03-21,1,cfb763496d9fc48751a27db4fd02aa2d,391fc6631aebcf3004804e51b40bcf1e,2018-03-06 09:30:43,49.95,15.10,cama_mesa_banho,38.0,168.0,2.0,350.0,25.0,9.0,19.0,bed_bath_table,528dfcc777a4bc47bfef5fd7b189cb2a,22775,rio de janeiro,RJ,14940,ibitinga,SP,1.0,credit_card,3.0,65.05,6d43c93b3681bcd2ab77d7599ec4b424,1.0,2018-03-23,2018-03-23 14:28:00,23,2,32 days 11:01:30,-7 days +03:41:31,32.0,7.0,1
55487,e75fa6144e2d8bfb834bba12ac534788,b76ebec5710cf10fdcf3a90c9d0315b3,delivered,2018-03-07 09:24:13,2018-03-07 09:35:30,2018-03-08 23:58:19,2018-04-07 00:04:49,2018-04-04,1,2abe986592541f0d9448fe0af86903ee,8b28d096634035667e8263d57ba3368c,2018-03-13 09:35:30,49.90,22.06,utilidades_domesticas,56.0,266.0,4.0,300.0,16.0,2.0,11.0,housewares,701b3fca6c8de04d31f53701b17114f2,78300,tangara da serra,MT,12243,sao jose dos campos,SP,1.0,credit_card,1.0,71.96,05237d6696ecbd99bc7393251c3b910c,1.0,2018-04-06,2018-04-06 12:57:25,7,3,30 days 14:40:36,-4 days +23:55:11,30.0,4.0,1
8360,1ddbb173ad5dee4433a9825491aa8f97,5c23fa18c25e09e15eb83f2569a914f7,delivered,2017-12-05 11:03:48,2017-12-05 11:30:44,2017-12-06 19:37:26,2017-12-13 11:38:54,2018-01-05,1,f70a5d9b1b6d4fac3e2b7da556700b33,fa1a9dec3a9940c072684a46728bf1fc,2017-12-11 11:15:33,99.90,16.46,pet_shop,56.0,1143.0,2.0,7700.0,50.0,20.0,40.0,pet_shop,2e49d8c29da227669fcdaafb6c2af0cd,8730,mogi das cruzes,SP,88820,icara,SC,1.0,credit_card,2.0,116.36,b3d38e63a4dc7c31b2347a7c17bcdbbd,5.0,2017-12-14,2017-12-14 20:38:37,5,12,8 days 00:35:06,22 days 12:21:06,8.0,-22.0,0

In [47]:
another_sales_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118310 entries, 0 to 118309
Data columns (total 45 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       118310 non-null  object
 1   customer_id                    118310 non-null  object
 2   order_status                   118310 non-null  object
 3   order_purchase_timestamp       118310 non-null  datetime64[ns]
 4   order_approved_at              118295 non-null  datetime64[ns]
 5   order_delivered_carrier_date   117056 non-null  datetime64[ns]
 6   order_delivered_customer_date  115722 non-null  datetime64[ns]
 7   order_estimated_delivery_date  118310 non-null  datetime64[ns]
 8   order_item_id                  118310 non-null  int64
 9   product_id                     118310 non-null  object
 10  seller_id                      118310 non-null  object
 11  shipping_limit_date            118310 non-null  datetime64[ns]
 12  price                          118310 non-null  float64
 13  freight_value                  118310 non-null  float64
 14  product_category_name          116601 non-null  object
 15  product_name_lenght            116601 non-null  float64
 16  product_description_lenght     116601 non-null  float64
 17  product_photos_qty             116601 non-null  float64
 18  product_weight_g               118290 non-null  float64
 19  product_length_cm              118290 non-null  float64
 20  product_height_cm              118290 non-null  float64
 21  product_width_cm               118290 non-null  float64
 22  product_category_name_english  116576 non-null  object
 23  customer_unique_id             118310 non-null  object
 24  customer_zip_code_prefix       118310 non-null  int64
 25  customer_city                  118310 non-null  object
 26  customer_state                 118310 non-null  object
 27  seller_zip_code_prefix         118310 non-null  int64
 28  seller_city                    118310 non-null  object
 29  seller_state                   118310 non-null  object
 30  payment_sequential             118307 non-null  float64
 31  payment_type                   118307 non-null  object
 32  payment_installments           118307 non-null  float64
 33  payment_value                  118307 non-null  float64
 34  review_id                      117332 non-null  object
 35  review_score                   117332 non-null  float64
 36  review_creation_date           117332 non-null  datetime64[ns]
 37  review_answer_timestamp        117332 non-null  datetime64[ns]
 38  day                            118310 non-null  int32
 39  month                          118310 non-null  int32
 40  purchase_to_delivery           115722 non-null  timedelta64[ns]
 41  estimated_to_delivery          115722 non-null  timedelta64[ns]
 42  purchase_to_delivery_days      115722 non-null  float64
 43  delivery_delay_days            115722 non-null  float64
 44  is_delayed                     118310 non-null  int64
dtypes: datetime64[ns](8), float64(15), int32(2), int64(4), object(14), timedelta64[ns](2)
memory usage: 39.7+ MB

In [48]:
# Add the "delivery_time_days" column
another_sales_test['delivery_time_days'] = (
    another_sales_test['order_delivered_customer_date'] - 
    another_sales_test['order_purchase_timestamp']
).dt.days

In [49]:
# Add the "is_delayed" flag
another_sales_test['is_delayed2'] = (
    another_sales_test['order_delivered_customer_date'] > 
    another_sales_test['order_estimated_delivery_date']
).astype(int)

In [50]:
another_sales_test.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name_english,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,seller_zip_code_prefix,seller_city,seller_state,payment_sequential,payment_type,payment_installments,payment_value,review_id,review_score,review_creation_date,review_answer_timestamp,day,month,purchase_to_delivery,estimated_to_delivery,purchase_to_delivery_days,delivery_delay_days,is_delayed,delivery_time_days,is_delayed2
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0,housewares,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,9350,maua,SP,1.0,credit_card,1.0,18.12,a54f0611adc9ed256b57ede6b6eb5114,4.0,2017-10-11,2017-10-12 03:43:48,2,10,8 days 10:28:40,7 days 02:34:47,8.0,-7.0,0,8.0,0
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0,housewares,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,9350,maua,SP,3.0,voucher,1.0,2.00,a54f0611adc9ed256b57ede6b6eb5114,4.0,2017-10-11,2017-10-12 03:43:48,2,10,8 days 10:28:40,7 days 02:34:47,8.0,-7.0,0,8.0,0
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0,housewares,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,9350,maua,SP,2.0,voucher,1.0,18.59,a54f0611adc9ed256b57ede6b6eb5114,4.0,2017-10-11,2017-10-12 03:43:48,2,10,8 days 10:28:40,7 days 02:34:47,8.0,-7.0,0,8.0,0
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,1,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.70,22.76,perfumaria,29.0,178.0,1.0,400.0,19.0,13.0,19.0,perfumery,af07308b275d755c9edb36a90c618231,47813,barreiras,BA,31570,belo horizonte,SP,1.0,boleto,1.0,141.46,8d5266042046a06655c8db133d120ba5,4.0,2018-08-08,2018-08-08 18:37:50,24,7,13 days 18:46:08,5 days 08:32:15,13.0,-5.0,0,13.0,0
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,1,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-13 08:55:23,159.90,19.22,automotivo,46.0,232.0,1.0,420.0,24.0,19.0,21.0,auto,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO,14840,guariba,SP,1.0,credit_card,3.0,179.12,e73b67b67587f7644d5bd1a52deb1b01,5.0,2018-08-18,2018-08-22 19:07:58,8,8,9 days 09:27:40,17 days 05:53:31,9.0,-17.0,0,9.0,0

In [51]:
another_sales_test['is_delayed'].value_counts()

is_delayed
0    109242
1      9068
Name: count, dtype: int64

In [52]:
full_duplicates = another_sales_test.duplicated().sum()
print(f"Number of full row duplicates: {full_duplicates}")

Number of full row duplicates: 0

In [53]:
if full_duplicates > 0:
    print("Sample of full duplicates:")
    print(another_sales_test[another_sales_test.duplicated(keep=False)].head())
else:
    print("No full duplicates found in the DataFrame.")

No full duplicates found in the DataFrame.

In [54]:
order_counts = another_sales_test['order_id'].value_counts()
print("Orders with multiple rows (top 10):")
print(order_counts.head(10))

Orders with multiple rows (top 10):
order_id
895ab968e7bb0d5659d16cd74cd1650c    63
fedcd9f7ccdc8cba3a18defedd1a5547    38
fa65dad1b0e818e3ccc5cb0e39231352    29
ccf804e764ed5650cd8759557269dc13    26
a3725dfe487d359b5be08cac48b64ec5    24
6d58638e32674bebee793a47ac4cbadc    24
68986e4324f6a21481df4e6e89abcf01    24
c6492b842ac190db807c15aff21a7dd6    24
465c2e1bee4561cb39e0db8c5993aafc    24
285c2e15bebd4ac83635ccc563dc71f4    22
Name: count, dtype: int64

In [55]:
unique_orders = another_sales_test['order_id'].nunique()
total_rows = another_sales_test.shape[0]
print(f"Total rows: {total_rows}")
print(f"Unique order_ids: {unique_orders}")
print(f"Rows with repeated order_ids: {total_rows - unique_orders}")

Total rows: 118310
Unique order_ids: 98666
Rows with repeated order_ids: 19644

In [56]:
another_sales_test.shape

(118310, 47)

In [57]:
another_sales_test.dropna(inplace=True)

In [58]:
another_sales_test.shape

(113193, 47)

In [59]:
full_duplicates = another_sales_test.duplicated().sum()
print(f"Number of full row duplicates: {full_duplicates}")

Number of full row duplicates: 0

In [60]:
order_counts = another_sales_test['order_id'].value_counts()
print("Orders with multiple rows (top 10):")
print(order_counts.head(10))

Orders with multiple rows (top 10):
order_id
895ab968e7bb0d5659d16cd74cd1650c    63
fedcd9f7ccdc8cba3a18defedd1a5547    38
ccf804e764ed5650cd8759557269dc13    26
a3725dfe487d359b5be08cac48b64ec5    24
6d58638e32674bebee793a47ac4cbadc    24
c6492b842ac190db807c15aff21a7dd6    24
68986e4324f6a21481df4e6e89abcf01    24
465c2e1bee4561cb39e0db8c5993aafc    24
5a3b1c29a49756e75f1ef513383c0c12    22
285c2e15bebd4ac83635ccc563dc71f4    22
Name: count, dtype: int64

In [61]:
unique_orders = another_sales_test['order_id'].nunique()
total_rows = another_sales_test.shape[0]
print(f"Total rows: {total_rows}")
print(f"Unique order_ids: {unique_orders}")
print(f"Rows with repeated order_ids: {total_rows - unique_orders}")

Total rows: 113193
Unique order_ids: 94471
Rows with repeated order_ids: 18722

In [62]:
# so there is no full row that is duplicated

In [63]:
top_order = order_counts.index[0]
print(f"Rows for order_id {top_order}:")

Rows for order_id 895ab968e7bb0d5659d16cd74cd1650c:

In [64]:
another_sales_test[another_sales_test['order_id'] == top_order]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name_english,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,seller_zip_code_prefix,seller_city,seller_state,payment_sequential,payment_type,payment_installments,payment_value,review_id,review_score,review_creation_date,review_answer_timestamp,day,month,purchase_to_delivery,estimated_to_delivery,purchase_to_delivery_days,delivery_delay_days,is_delayed,delivery_time_days,is_delayed2
84910,895ab968e7bb0d5659d16cd74cd1650c,270c23a11d024a44c896d1894b261a83,delivered,2017-08-08 20:26:31,2017-08-08 20:43:31,2017-08-10 11:58:14,2017-08-14 12:46:18,2017-08-30,1,ebf9bc6cd600eadd681384e3116fda85,822166ed1e47908f7cfb49946d03c726,2017-08-14 20:43:31,12.99,23.21,cama_mesa_banho,37.0,86.0,2.0,1300.0,50.0,9.0,41.0,bed_bath_table,9a736b248f67d166d2fbb006bcb877c3,3227,sao paulo,SP,25803,tres rios,RJ,17.0,voucher,1.0,16.70,eef5dbca8d37dfce6db7d7b16dd0525e,5.0,2017-08-15,2017-08-17 22:17:55,8,8,5 days 16:19:47,15 days 11:13:42,5.0,-15.0,0,5.0,0
84911,895ab968e7bb0d5659d16cd74cd1650c,270c23a11d024a44c896d1894b261a83,delivered,2017-08-08 20:26:31,2017-08-08 20:43:31,2017-08-10 11:58:14,2017-08-14 12:46:18,2017-08-30,1,ebf9bc6cd600eadd681384e3116fda85,822166ed1e47908f7cfb49946d03c726,2017-08-14 20:43:31,12.99,23.21,cama_mesa_banho,37.0,86.0,2.0,1300.0,50.0,9.0,41.0,bed_bath_table,9a736b248f67d166d2fbb006bcb877c3,3227,sao paulo,SP,25803,tres rios,RJ,1.0,voucher,1.0,2.61,eef5dbca8d37dfce6db7d7b16dd0525e,5.0,2017-08-15,2017-08-17 22:17:55,8,8,5 days 16:19:47,15 days 11:13:42,5.0,-15.0,0,5.0,0
84912,895ab968e7bb0d5659d16cd74cd1650c,270c23a11d024a44c896d1894b261a83,delivered,2017-08-08 20:26:31,2017-08-08 20:43:31,2017-08-10 11:58:14,2017-08-14 12:46:18,2017-08-30,1,ebf9bc6cd600eadd681384e3116fda85,822166ed1e47908f7cfb49946d03c726,2017-08-14 20:43:31,12.99,23.21,cama_mesa_banho,37.0,86.0,2.0,1300.0,50.0,9.0,41.0,bed_bath_table,9a736b248f67d166d2fbb006bcb877c3,3227,sao paulo,SP,25803,tres rios,RJ,13.0,voucher,1.0,16.70,eef5dbca8d37dfce6db7d7b16dd0525e,5.0,2017-08-15,2017-08-17 22:17:55,8,8,5 days 16:19:47,15 days 11:13:42,5.0,-15.0,0,5.0,0
84913,895ab968e7bb0d5659d16cd74cd1650c,270c23a11d024a44c896d1894b261a83,delivered,2017-08-08 20:26:31,2017-08-08 20:43:31,2017-08-10 11:58:14,2017-08-14 12:46:18,2017-08-30,1,ebf9bc6cd600eadd681384e3116fda85,822166ed1e47908f7cfb49946d03c726,2017-08-14 20:43:31,12.99,23.21,cama_mesa_banho,37.0,86.0,2.0,1300.0,50.0,9.0,41.0,bed_bath_table,9a736b248f67d166d2fbb006bcb877c3,3227,sao paulo,SP,25803,tres rios,RJ,16.0,voucher,1.0,16.70,eef5dbca8d37dfce6db7d7b16dd0525e,5.0,2017-08-15,2017-08-17 22:17:55,8,8,5 days 16:19:47,15 days 11:13:42,5.0,-15.0,0,5.0,0
84914,895ab968e7bb0d5659d16cd74cd1650c,270c23a11d024a44c896d1894b261a83,delivered,2017-08-08 20:26:31,2017-08-08 20:43:31,2017-08-10 11:58:14,2017-08-14 12:46:18,2017-08-30,1,ebf9bc6cd600eadd681384e3116fda85,822166ed1e47908f7cfb49946d03c726,2017-08-14 20:43:31,12.99,23.21,cama_mesa_banho,37.0,86.0,2.0,1300.0,50.0,9.0,41.0,bed_bath_table,9a736b248f67d166d2fbb006bcb877c3,3227,sao paulo,SP,25803,tres rios,RJ,19.0,voucher,1.0,0.24,eef5dbca8d37dfce6db7d7b16dd0525e,5.0,2017-08-15,2017-08-17 22:17:55,8,8,5 days 16:19:47,15 days 11:13:42,5.0,-15.0,0,5.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84968,895ab968e7bb0d5659d16cd74cd1650c,270c23a11d024a44c896d1894b261a83,delivered,2017-08-08 20:26:31,2017-08-08 20:43:31,2017-08-10 11:58:14,2017-08-14 12:46:18,2017-08-30,3,5ddab10d5e0a23acb99acf56b62b3276,3d0cd21d41671c46f82cd11176bf7277,2017-08-14 20:43:31,83.80,5.12,utilidades_domesticas,56.0,548.0,8.0,450.0,30.0,20.0,11.0,housewares,9a736b248f67d166d2fbb006bcb877c3,3227,sao paulo,SP,89217,joinville,SC,15.0,voucher,1.0,16.70,eef5dbca8d37dfce6db7d7b16dd0525e,5.0,2017-08-15,2017-08-17 22:17:55,8,8,5 days 16:19:47,15 days 11:13:42,5.0,-15.0,0,5.0,0
84969,895ab968e7bb0d5659d16cd74cd1650c,270c23a11d024a44c896d1894b261a83,delivered,2017-08-08 20:26:31,2017-08-08 20:43:31,2017-08-10 11:58:14,2017-08-14 12:46:18,2017-08-30,3,5ddab10d5e0a23acb99acf56b62b3276,3d0cd21d41671c46f82cd11176bf7277,2017-08-14 20:43:31,83.80,5.12,utilidades_domesticas,56.0,548.0,8.0,450.0,30.0,20.0,11.0,housewares,9a736b248f67d166d2fbb006bcb877c3,3227,sao paulo,SP,89217,joinville,SC,20.0,voucher,1.0,4.61,eef5dbca8d37dfce6db7d7b16dd0525e,5.0,2017-08-15,2017-08-17 22:17:55,8,8,5 days 16:19:47,15 days 11:13:42,5.0,-15.0,0,5.0,0
84970,895ab968e7bb0d5659d16cd74cd1650c,270c23a11d024a44c896d1894b261a83,delivered,2017-08-08 20:26:31,2017-08-08 20:43:31,2017-08-10 11:58:14,2017-08-14 12:46:18,2017-08-30,3,5ddab10d5e0a23acb99acf56b62b3276,3d0cd21d41671c46f82cd11176bf7277,2017-08-14 20:43:31,83.80,5.12,utilidades_domesticas,56.0,548.0,8.0,450.0,30.0,20.0,11.0,housewares,9a736b248f67d166d2fbb006bcb877c3,3227,sao paulo,SP,89217,joinville,SC,14.0,voucher,1.0,16.70,eef5dbca8d37dfce6db7d7b16dd0525e,5.0,2017-08-15,2017-08-17 22:17:55,8,8,5 days 16:19:47,15 days 11:13:42,5.0,-15.0,0,5.0,0
84971,895ab968e7bb0d5659d16cd74cd1650c,270c23a11d024a44c896d1894b261a83,delivered,2017-08-08 20:26:31,2017-08-08 20:43:31,2017-08-10 11:58:14,2017-08-14 12:46:18,2017-08-30,3,5ddab10d5e0a23acb99acf56b62b3276,3d0cd21d41671c46f82cd11176bf7277,2017-08-14 20:43:31,83.80,5.12,utilidades_domesticas,56.0,548.0,8.0,450.0,30.0,20.0,11.0,housewares,9a736b248f67d166d2fbb006bcb877c3,3227,sao paulo,SP,89217,joinville,SC,9.0,voucher,1.0,2.61,eef5dbca8d37dfce6db7d7b16dd0525e,5.0,2017-08-15,2017-08-17 22:17:55,8,8,5 days 16:19:47,15 days 11:13:42,5.0,-15.0,0,5.0,0
84972,895ab968e7bb0d5659d16cd74cd1650c,270c23a11d024a44c896d1894b261a83,delivered,2017-08-08 20:26:31,2017-08-08 20:43:31,2017-08-10 11:58:14,2017-08-14 12:46:18,2017-08-30,3,5ddab10d5e0a23acb99acf56b62b3276,3d0cd21d41671c46f82cd11176bf7277,2017-08-14 20:43:31,83.80,5.12,utilidades_domesticas,56.0,548.0,8.0,450.0,30.0,20.0,11.0,housewares,9a736b248f67d166d2fbb006bcb877c3,3227,sao paulo,SP,89217,joinville,SC,6.0,voucher,1.0,2.61,eef5dbca8d37dfce6db7d7b16dd0525e,5.0,2017-08-15,2017-08-17 22:17:55,8,8,5 days 16:19:47,15 days 11:13:42,5.0,-15.0,0,5.0,0

In [65]:
another_sales_test.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date',
       'price', 'freight_value', 'product_category_name',
       'product_name_lenght', 'product_description_lenght',
       'product_photos_qty', 'product_weight_g', 'product_length_cm',
       'product_height_cm', 'product_width_cm',
       'product_category_name_english', 'customer_unique_id',
       'customer_zip_code_prefix', 'customer_city', 'customer_state',
       'seller_zip_code_prefix', 'seller_city', 'seller_state',
       'payment_sequential', 'payment_type', 'payment_installments',
       'payment_value', 'review_id', 'review_score', 'review_creation_date',
       'review_answer_timestamp', 'day', 'month', 'purchase_to_delivery',
       'estimated_to_delivery', 'purchase_to_delivery_days',
       'delivery_delay_days', 'is_delayed', 'delivery_time_days',
       'is_delayed2'],
      dtype='object')

In [66]:
another_sales_test.to_csv('sales_clean.csv', index=False)

In [67]:
another_sales_test.to_csv('sales_clean_csv.csv', index=False)

In [68]:
another_sales_test.info()

<class 'pandas.core.frame.DataFrame'>
Index: 113193 entries, 0 to 118309
Data columns (total 47 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       113193 non-null  object
 1   customer_id                    113193 non-null  object
 2   order_status                   113193 non-null  object
 3   order_purchase_timestamp       113193 non-null  datetime64[ns]
 4   order_approved_at              113193 non-null  datetime64[ns]
 5   order_delivered_carrier_date   113193 non-null  datetime64[ns]
 6   order_delivered_customer_date  113193 non-null  datetime64[ns]
 7   order_estimated_delivery_date  113193 non-null  datetime64[ns]
 8   order_item_id                  113193 non-null  int64
 9   product_id                     113193 non-null  object
 10  seller_id                      113193 non-null  object
 11  shipping_limit_date            113193 non-null  datetime64[ns]
 12  price                          113193 non-null  float64
 13  freight_value                  113193 non-null  float64
 14  product_category_name          113193 non-null  object
 15  product_name_lenght            113193 non-null  float64
 16  product_description_lenght     113193 non-null  float64
 17  product_photos_qty             113193 non-null  float64
 18  product_weight_g               113193 non-null  float64
 19  product_length_cm              113193 non-null  float64
 20  product_height_cm              113193 non-null  float64
 21  product_width_cm               113193 non-null  float64
 22  product_category_name_english  113193 non-null  object
 23  customer_unique_id             113193 non-null  object
 24  customer_zip_code_prefix       113193 non-null  int64
 25  customer_city                  113193 non-null  object
 26  customer_state                 113193 non-null  object
 27  seller_zip_code_prefix         113193 non-null  int64
 28  seller_city                    113193 non-null  object
 29  seller_state                   113193 non-null  object
 30  payment_sequential             113193 non-null  float64
 31  payment_type                   113193 non-null  object
 32  payment_installments           113193 non-null  float64
 33  payment_value                  113193 non-null  float64
 34  review_id                      113193 non-null  object
 35  review_score                   113193 non-null  float64
 36  review_creation_date           113193 non-null  datetime64[ns]
 37  review_answer_timestamp        113193 non-null  datetime64[ns]
 38  day                            113193 non-null  int32
 39  month                          113193 non-null  int32
 40  purchase_to_delivery           113193 non-null  timedelta64[ns]
 41  estimated_to_delivery          113193 non-null  timedelta64[ns]
 42  purchase_to_delivery_days      113193 non-null  float64
 43  delivery_delay_days            113193 non-null  float64
 44  is_delayed                     113193 non-null  int64
 45  delivery_time_days             113193 non-null  float64
 46  is_delayed2                    113193 non-null  int64
dtypes: datetime64[ns](8), float64(16), int32(2), int64(5), object(14), timedelta64[ns](2)
memory usage: 40.6+ MB

In [69]:
another_sales_test.info()

<class 'pandas.core.frame.DataFrame'>
Index: 113193 entries, 0 to 118309
Data columns (total 47 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       113193 non-null  object
 1   customer_id                    113193 non-null  object
 2   order_status                   113193 non-null  object
 3   order_purchase_timestamp       113193 non-null  datetime64[ns]
 4   order_approved_at              113193 non-null  datetime64[ns]
 5   order_delivered_carrier_date   113193 non-null  datetime64[ns]
 6   order_delivered_customer_date  113193 non-null  datetime64[ns]
 7   order_estimated_delivery_date  113193 non-null  datetime64[ns]
 8   order_item_id                  113193 non-null  int64
 9   product_id                     113193 non-null  object
 10  seller_id                      113193 non-null  object
 11  shipping_limit_date            113193 non-null  datetime64[ns]
 12  price                          113193 non-null  float64
 13  freight_value                  113193 non-null  float64
 14  product_category_name          113193 non-null  object
 15  product_name_lenght            113193 non-null  float64
 16  product_description_lenght     113193 non-null  float64
 17  product_photos_qty             113193 non-null  float64
 18  product_weight_g               113193 non-null  float64
 19  product_length_cm              113193 non-null  float64
 20  product_height_cm              113193 non-null  float64
 21  product_width_cm               113193 non-null  float64
 22  product_category_name_english  113193 non-null  object
 23  customer_unique_id             113193 non-null  object
 24  customer_zip_code_prefix       113193 non-null  int64
 25  customer_city                  113193 non-null  object
 26  customer_state                 113193 non-null  object
 27  seller_zip_code_prefix         113193 non-null  int64
 28  seller_city                    113193 non-null  object
 29  seller_state                   113193 non-null  object
 30  payment_sequential             113193 non-null  float64
 31  payment_type                   113193 non-null  object
 32  payment_installments           113193 non-null  float64
 33  payment_value                  113193 non-null  float64
 34  review_id                      113193 non-null  object
 35  review_score                   113193 non-null  float64
 36  review_creation_date           113193 non-null  datetime64[ns]
 37  review_answer_timestamp        113193 non-null  datetime64[ns]
 38  day                            113193 non-null  int32
 39  month                          113193 non-null  int32
 40  purchase_to_delivery           113193 non-null  timedelta64[ns]
 41  estimated_to_delivery          113193 non-null  timedelta64[ns]
 42  purchase_to_delivery_days      113193 non-null  float64
 43  delivery_delay_days            113193 non-null  float64
 44  is_delayed                     113193 non-null  int64
 45  delivery_time_days             113193 non-null  float64
 46  is_delayed2                    113193 non-null  int64
dtypes: datetime64[ns](8), float64(16), int32(2), int64(5), object(14), timedelta64[ns](2)
memory usage: 40.6+ MB